//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzariaDoZe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PizzariaDoZe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string btnCancelar_Text {
            get {
                return ResourceManager.GetString("btnCancelar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        internal static string btnSalvar_Text {
            get {
                return ResourceManager.GetString("btnSalvar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap funcionarios {
            get {
                object obj = ResourceManager.GetObject("funcionarios", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home1 {
            get {
                object obj = ResourceManager.GetObject("home1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        internal static string labalCategoria_Text {
            get {
                return ResourceManager.GetString("labalCategoria.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        internal static string labelBairro_Text {
            get {
                return ResourceManager.GetString("labelBairro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem Vindo(a).
        /// </summary>
        internal static string labelBemVindo_Text {
            get {
                return ResourceManager.GetString("labelBemVindo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Funcionarios.
        /// </summary>
        internal static string labelCadastraFuncionario_Text {
            get {
                return ResourceManager.GetString("labelCadastraFuncionario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Cliente.
        /// </summary>
        internal static string labelCadastrarCliente_Text {
            get {
                return ResourceManager.GetString("labelCadastrarCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Funcionário.
        /// </summary>
        internal static string labelCadastrarFuncionario_Text {
            get {
                return ResourceManager.GetString("labelCadastrarFuncionario.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Ingrediente.
        /// </summary>
        internal static string labelCadastrarIngrediente_Text {
            get {
                return ResourceManager.GetString("labelCadastrarIngrediente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Produto.
        /// </summary>
        internal static string labelCadastrarProduto_Text {
            get {
                return ResourceManager.GetString("labelCadastrarProduto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Sabor.
        /// </summary>
        internal static string labelCadastrarSabor_Text {
            get {
                return ResourceManager.GetString("labelCadastrarSabor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Sabor.
        /// </summary>
        internal static string labelCadastrarValor_Text {
            get {
                return ResourceManager.GetString("labelCadastrarValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Clientes.
        /// </summary>
        internal static string labelCadastroCliente_Text {
            get {
                return ResourceManager.GetString("labelCadastroCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Ingredientes.
        /// </summary>
        internal static string labelCadastroIngrediente_Text {
            get {
                return ResourceManager.GetString("labelCadastroIngrediente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Produtos.
        /// </summary>
        internal static string labelCadastroProdutos_Text {
            get {
                return ResourceManager.GetString("labelCadastroProdutos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Sabores.
        /// </summary>
        internal static string labelCadastroSabores_Text {
            get {
                return ResourceManager.GetString("labelCadastroSabores.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Valores.
        /// </summary>
        internal static string labelCadastroValores_Text {
            get {
                return ResourceManager.GetString("labelCadastroValores.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carteira de Motorista.
        /// </summary>
        internal static string labelCarteiraMotorista_Text {
            get {
                return ResourceManager.GetString("labelCarteiraMotorista.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        internal static string labelCEP_Text {
            get {
                return ResourceManager.GetString("labelCEP.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        internal static string labelCidade_Text {
            get {
                return ResourceManager.GetString("labelCidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        internal static string labelClientes_Text {
            get {
                return ResourceManager.GetString("labelClientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        internal static string labelComplemento_Text {
            get {
                return ResourceManager.GetString("labelComplemento.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        internal static string labelConfiguracoes {
            get {
                return ResourceManager.GetString("labelConfiguracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        internal static string labelCPF_Text {
            get {
                return ResourceManager.GetString("labelCPF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string labelEmail_Text {
            get {
                return ResourceManager.GetString("labelEmail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        internal static string labelEndereco_Text {
            get {
                return ResourceManager.GetString("labelEndereco.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string labelEstado_Text {
            get {
                return ResourceManager.GetString("labelEstado.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionários.
        /// </summary>
        internal static string labelFuncionarios_Text {
            get {
                return ResourceManager.GetString("labelFuncionarios.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        internal static string labelGrupo_Text {
            get {
                return ResourceManager.GetString("labelGrupo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string labelId_Text {
            get {
                return ResourceManager.GetString("labelId.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem.
        /// </summary>
        internal static string labelImagem_Text {
            get {
                return ResourceManager.GetString("labelImagem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredientes.
        /// </summary>
        internal static string labelIngredientes_Text {
            get {
                return ResourceManager.GetString("labelIngredientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string labelInicio_Text {
            get {
                return ResourceManager.GetString("labelInicio.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro.
        /// </summary>
        internal static string labelLogradouro_Text {
            get {
                return ResourceManager.GetString("labelLogradouro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matricula.
        /// </summary>
        internal static string labelMatricula_Text {
            get {
                return ResourceManager.GetString("labelMatricula.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ML.
        /// </summary>
        internal static string labelMl_Text {
            get {
                return ResourceManager.GetString("labelMl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string labelNome_Text {
            get {
                return ResourceManager.GetString("labelNome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero.
        /// </summary>
        internal static string labelNumero_Text {
            get {
                return ResourceManager.GetString("labelNumero.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação.
        /// </summary>
        internal static string labelObservacao_Text {
            get {
                return ResourceManager.GetString("labelObservacao.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string labelPais_Text {
            get {
                return ResourceManager.GetString("labelPais.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos.
        /// </summary>
        internal static string labelProdutos_Text {
            get {
                return ResourceManager.GetString("labelProdutos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string labelReultadosInicio_Text {
            get {
                return ResourceManager.GetString("labelReultadosInicio.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabores.
        /// </summary>
        internal static string labelSabores_Text {
            get {
                return ResourceManager.GetString("labelSabores.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        internal static string labelSenha_Text {
            get {
                return ResourceManager.GetString("labelSenha.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho.
        /// </summary>
        internal static string labelTamanho_Text {
            get {
                return ResourceManager.GetString("labelTamanho.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        internal static string labelTelefone_Text {
            get {
                return ResourceManager.GetString("labelTelefone.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string labelTipo_Text {
            get {
                return ResourceManager.GetString("labelTipo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validade.
        /// </summary>
        internal static string labelValidade_Text {
            get {
                return ResourceManager.GetString("labelValidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Borda.
        /// </summary>
        internal static string labelValorBorda_Text {
            get {
                return ResourceManager.GetString("labelValorBorda.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar Senha.
        /// </summary>
        internal static string labelVerificarSenha_Text {
            get {
                return ResourceManager.GetString("labelVerificarSenha.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        internal static string radioBtnGrupoAdministrador_Text {
            get {
                return ResourceManager.GetString("radioBtnGrupoAdministrador.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atendente.
        /// </summary>
        internal static string radioBtnGrupoAtendente_Text {
            get {
                return ResourceManager.GetString("radioBtnGrupoAtendente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entregador.
        /// </summary>
        internal static string radioBtnGrupoEntregador_Text {
            get {
                return ResourceManager.GetString("radioBtnGrupoEntregador.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap users_alt {
            get {
                object obj = ResourceManager.GetObject("users-alt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap users_solid {
            get {
                object obj = ResourceManager.GetObject("users-solid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
